### ISSUE TITLE
Reference missing?

### ISSUE THREAD

**Issue by benwilcock** [idugalic/micro-company#1]
Your 'How it Works' section in your readme looks like a carbon copy of that posted on my blog. I don't mind if you're using it, that's fine, but a credit or a reference would be nice?!

My blog entry is here: https://benwilcock.wordpress.com/2016/06/20/microservices-with-spring-boot-axon-cqrses-and-docker/

**Comment by idugalic** [comment]
I just added the reference to your new blog post.
https://github.com/idugalic/micro-company/commit/8bb5a13a1d61830d7f884c100b98c0f312c292aa
