### ISSUE TITLE
cannot copy logs from a container to local file system

### ISSUE THREAD

**Issue by chiefeweight** [idugalic/micro-company#10]
Hello, I try to do some analysis on micro-company, so I need to copy logs from a container to local file system. I follow the instructions to run micro-company on a docker swarm as a local cluster, and logs can be printed out using the command "docker logs CONTAINER_ID", but cannot be copied to a local directory, for example, using the command "docker container cp CONTAINER_ID:CONTAINER_ID-json.log d:\\". The git-bash tells me that "No such container:path".

Here are some informations corresponding to several commands:
**1.  docker container ls**
Three containers: 
_"95c91ae8e73d"_ with the name _"micro-company_adminserver.1.n01flae4qim93hiv622a5bfqy"_
_"2624d8811748"_ with the name _"micro-company_api-gateway.1.la7ep2g9sd2idn42t0s8edq1z"_
_"28ed199ed5fc"_ with the name _"micro-company_command-side-blog.1.ny7mixus2ylqpl09ce8mdl2cr"_

**2.docker container inspect 2624d8811748 | grep 'log'**
Search the log file path within container 2624d8811748(api-gateway), it shows:
_"LogPath": "/mnt/sda1/var/lib/docker/containers/2624d88117486af506199563a20dcfc525f67074c066ec8f84610ba8454de3d3/2624d88117486af506199563a20dcfc525f67074c066ec8f84610ba8454de3d3-json.log",_

**3.docker container cp 2624d8811748:2624d88117486af506199563a20dcfc525f67074c066ec8f84610ba8454de3d3-json.log d:\\**
Copy the log file from the container to d:\\, it shows:
_Error: No such container:path: 2624d8811748:2624d88117486af506199563a20dcfc525f67074c066ec8f84610ba8454de3d3-json.log_

**4.docker container cp 2624d8811748:\\ d:\\**
Copy all files from this container to d:\\. This operation can be done successfully, but there are no "log" files in it.
 
Should I use some other commands to export the log file, or are there any other ways to monitor micro-company?

Thank you!

PS:Sometimes the post command reaches timed out. I don't know why, just delete all virtual network and restart PC, then all fixed(usually).

**Comment by idugalic** [comment]
It depends how you want to make sense of the logs. You can use a rich log aggregation platform like [ELK](https://logz.io/learn/complete-guide-elk-stack/) to collect and index all your logs from your different microservice instances.

With Docker Compose, we gain the command, ‘docker-compose logs‘. This command stream the log output of running services, of all containers defined in our ‘docker-compose.yml‘ file.

There should be an example of aggregating the logs from all the services deployed to [Docker Swarm](https://github.com/idugalic/micro-company#experimental-features)

Monitoring is very important, but it is not covered in details (production ready) within this sample project. You can check some of the docs:
- https://programmaticponderings.com/2015/08/02/log-aggregation-visualization-and-analysis-of-microservices-using-elk-stack-and-logspout/

**Comment by chiefeweight** [comment]
> It depends how you want to make sense of the logs. You can use a rich log aggregation platform like [ELK](https://logz.io/learn/complete-guide-elk-stack/) to collect and index all your logs from your different microservice instances.
> 
> With Docker Compose, we gain the command, ‘docker-compose logs‘. This command stream the log output of running services, of all containers defined in our ‘docker-compose.yml‘ file.
> 
> There should be an example of aggregating the logs from all the services deployed to [Docker Swarm](https://github.com/idugalic/micro-company#experimental-features)
> 
> Monitoring is very important, but it is not covered in details (production ready) within this sample project. You can check some of the docs:
> 
> * https://programmaticponderings.com/2015/08/02/log-aggregation-visualization-and-analysis-of-microservices-using-elk-stack-and-logspout/

Thank you! I am trying ELK now.
