### ISSUE TITLE
query side didn't receive event。

### ISSUE THREAD

**Issue by xwayway** [idugalic/micro-company#9]
Use cloud to start the microservices. Why do I send the command, the command on the command side of the log command sent to commandBus, but the query end did not receive event。it worked in starting by monolithic。

**Comment by idugalic** [comment]
@weechang thank you for opening the issue.

What run method have you used?

- [Run microservices on localhost via docker](https://github.com/idugalic/micro-company#run-microservices-on-localhost-via-docker)
- [Run microservices on Docker Swarm (mode) - Local cluster](https://github.com/idugalic/micro-company#run-microservices-on-docker-swarm-mode---local-cluster)
- [Run microservices on Docker Swarm (mode) - AWS cluster](https://github.com/idugalic/micro-company#run-microservices-on-docker-swarm-mode---aws-cluster)
- [Run microservices on Pivotal Cloud Foundry - PCF Dev
](https://github.com/idugalic/micro-company#run-microservices-on-pivotal-cloud-foundry---pcf-dev)
NOTE: Microservices deployment is using 'RabbitMQ' to pass events to the query side. Once I know what running method you have used, I can investigate. Thanks !
